name: snake
description: A web app that uses AngularDart
version: 0.0.1

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.30

transformers:
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter
